Adding JWT validation
Adding JWT validation but having a rough go of it. The @wraps decorator
which is commonly used to copy over the meta data of the wrapped
function is resulting in a strange error message:
```
Traceback (most recent call last):
  File "/Users/n0_3nnui/Projects/ereadingtool/ereadingtool/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/n0_3nnui/Projects/ereadingtool/ereadingtool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/n0_3nnui/Projects/ereadingtool/ereadingtool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/n0_3nnui/Projects/ereadingtool/ereadingtool/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/n0_3nnui/Projects/ereadingtool/ereadingtool/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: update_wrapper() got an unexpected keyword argument 'pk'
```

Once that is ironed out (may have to copy over the fields manually) we
can support arguments provided to the wrapped function. That means we
can send back generic HttpResponse objects with appropriate status codes
and corresponding error messages. These error messages would be added to
the function which wraps the decorator. You may have seen these before;
functions look like decorators but actually execute the function before
creating the decorator. They look like this:

@decorator('string param')
def foo():
    ...

This way we can provide parameters to the wrapped function like so:

@decorator(error={error: "Forbidden!"})
def potentially_hazardous():
    try:
        foo()
    except:
        HttpResponse(json.dumps(error))

Basically, custom errors for each wrapped function.